#!/usr/bin/env bash

# BSD 3-Clause License

# Copyright (c) 2017, Maxim Konakov
# All rights reserved.

# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:

# * Redistributions of source code must retain the above copyright notice, this
#   list of conditions and the following disclaimer.

# * Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.

# * Neither the name of the copyright holder nor the names of its
#   contributors may be used to endorse or promote products derived from
#   this software without specific prior written permission.

# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# version
declare -r VERSION=0.0.1

# helper functions
function _check_program() {
	# https://stackoverflow.com/questions/592620/check-if-a-program-exists-from-a-bash-script
	command -p -v "$@" >/dev/null 2>&1 || { echo "ERROR: Program \"$@\" is not found." >&2 ; exit 1 ; }
}

function _show_usage() {
	cat <<-EOF >&2
	Usage: $0 [OPTION]... FILE
	Extracts text from a scanned pdf or djvu document FILE.
	Options:
	  -f N     first page number (optional, default: 1)
	  -l N     last page number (optional, default: last page of the document)
	  -L LANG  document language (optional, default: 'eng')
	  -o FILE  output file name (optional, default: stdout)
	  -w DIR   working directory (optional, default: a temporary directory)
	  -h       display this help and exit
	  -v       output version information and exit
	EOF
}

function _ddjvu_exit() {
	head -q -n 1 "$1" | sed 's/^ddjvu:[[:space:]]*\[[^]]*\]/ddjvu:/g' >&2
	exit 1
}

# tesseract
_check_program tesseract

declare -r TESS_VER=$(tesseract -v 2>&1 | head -q -n 1 | cut -s -d " " -f 2 )

if [[ ${TESS_VER%%.[0-9]*} -lt 3 ]]	# major >= 3
then
	echo "ERROR: Current \"tesseract\" version $TESS_VER is not supported" >&2
	exit 1
fi

# options
while getopts "f:l:L:o:w:vh" opt
do
	case $opt in
		f)	case $OPTARG in
				''|*[!0-9]*)	echo "Invalid parameter for -$opt option: $OPTARG" >&2 ; exit 1 ;;
				*)				FIRST_PAGE=$OPTARG ;;
			esac ;;
		l)	case $OPTARG in
				''|*[!0-9]*)	echo "Invalid parameter for -$opt option: $OPTARG" >&2 ; exit 1 ;;
				*)				LAST_PAGE=$OPTARG ;;
			esac ;;
		L)	OCR_LANG=$OPTARG ;;
		o)	declare -r OUT_FILE="$OPTARG" ;;
		w)	WORK_DIR=$OPTARG ;;
		v)	echo v$VERSION ; exit 1 ;;
		h)	_show_usage ; exit 1 ;;
		\?)	exit 1 ;;
	esac
done

shift $((OPTIND-1)) # remove parsed options and args from $@ list

# input file
case $# in
	1)	declare -r INPUT_FILE=$1
		[[ -f "$INPUT_FILE" ]] || { echo "ERROR: File not found: $INPUT_FILE" >&2 ; exit 1 ; } ;;

	0)	printf "ERROR: Input file is not specified\n\n" >&2 ; _show_usage ; exit 1 ;;
	*)	echo "ERROR: Cannot process more than one input file: $@" >&2 ; exit 1 ;;
esac

# working directory
if [[ -n "$WORK_DIR" ]]
then
	WORK_DIR=$(echo $WORK_DIR | sed 's:/*$::')	# remove all trailing slashes

	if [[ -z "$WORK_DIR" ]]
	then
		echo "ERROR: Invalid name for working directory" >&2
		exit 1
	elif [[ ! -d "$WORK_DIR" ]]	# create if does not exists
	then
		mkdir "$WORK_DIR" || exit 1
	else	# clear if not empty
		find "$WORK_DIR" -maxdepth 1 -type f \
			\( -name \*.tif -o -name \*.tif.err -o -name \*.tif.txt -o -name ddjvu-error \) \
			-delete
	fi
else
	WORK_DIR=$(mktemp -d --tmpdir ocr.XXXXXXXXXX) || exit 1
	trap "rm -rf $WORK_DIR" 0 SIGINT SIGQUIT SIGTERM
fi

declare -r WORK_DIR

#defaults
declare -r OCR_LANG=${OCR_LANG:-eng}

# extract images
case "${INPUT_FILE##*.}" in
	PDF|pdf)	# pdfimages
		_check_program pdfimages

		if [[ -z $(pdfimages --help 2>&1 | grep -E '^\s+\-tiff\s+') ]]
		then
			echo "ERROR: Current version of \"pdfimages\" does not support .tiff output format" >&2
			exit 1
		fi

		pdfimages -tiff -f ${FIRST_PAGE:-1} -l ${LAST_PAGE:-5000} "$INPUT_FILE" "$WORK_DIR/img" || exit 1 ;;

	djvu)	# ddjvu
		_check_program ddjvu
		ddjvu -format=tiff -mode=black -eachpage -page=${FIRST_PAGE:-1}-${LAST_PAGE:-5000} "$INPUT_FILE" "$WORK_DIR/img-%05d.tif" 2>"$WORK_DIR/ddjvu-error" \
		|| _ddjvu_exit "$WORK_DIR/ddjvu-error" ;;

	*)	# error
		echo "ERROR: Unsupported file type: $INPUT_FILE" >&2 ; exit 1 ;;
esac

if [[ -z $(find "$WORK_DIR" -maxdepth 1 -type f -name \*.tif) ]]	# for some reason 'ls' finds nothing at this point
then
	echo "ERROR: No images extracted, something must have gone wrong" >&2
	exit 1
fi

# number of processors
NPROC=$(nproc) ; [ $? -ne 0 ] && exit 1 ; declare -r -i NPROC

# OCR
find "$WORK_DIR" -maxdepth 1 -type f -name \*.tif -print0 | xargs -0 -n 1 -P $NPROC -I % \
	sh -c "tesseract \"%\" \"%\" -l \"$OCR_LANG\" 2>\"%.err\" || exit 255"

if [[ $? -ne 0 ]]
then
	find "$WORK_DIR" -maxdepth 1 -type f -name \*.tif.err -exec grep -i -E '^ERROR:?\s+' "{}" \; >&2
	exit 1
fi

# output redirection
if [[ -n "$OUT_FILE" ]]	# https://stackoverflow.com/a/20564208
then
	exec 1<&-
	exec 1>"$OUT_FILE" || exit 1
fi

# output
find "$WORK_DIR" -maxdepth 1 -type f -name \*.tif.txt -print0 | sort -z | xargs -0 cat

